server.port = 8083

eureka.client.service-url.defaultZone =  http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Custom Queue, Exchange and Routing Key for Account Events
account.rabbitmq.queue.name=user-created-queue
account.rabbitmq.exchange.name=user-exchange
account.rabbitmq.routing.key=user.created


spring.datasource.url = jdbc:mysql://localhost:3306/user_db?createDatabaseIfNotExist=true
spring.datasource.username =prosper
spring.datasource.password =prosper
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show.sql = true


spring.jpa.hibernate.ddl-auto=update

# SMTP Configuration for Email Sending (Mailtrap example)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=75ad47954d9b23
spring.mail.password=d65a8744c0de73
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.mailtrap.io
spring.mail.test-connection=true
spring.mail.properties.mail.from=chenjobober00@gmail.com